version: "3"

services: 
    app:
        build: .
        command: npm start
        ports: 
            - "0:0:0:0:3333:3333"        
        env_file:
            - .env
        restart: unless-stopped